# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
common: &common
  adapter: postgresql
  encoding: utf-8
  username: postgres
  template: template0
  password: postgres 

development:
  <<: *common
  database: intercooler_rails_demo_dev 
  host: localhost

test:
  <<: *common
  database: intercooler_rails_demo_test 
  host: localhost

production:
  <<: *common
  database: intercooler_rails_demo_prod
